{{- if .Values.persistance.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistance.storageClass }}
  accessModes: {{ .Values.persistance.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistance.size }}
{{- end }}